package it.polimi.se2019.view;

public enum ClientState {
    TYPINGNICKNAME,
    CHOOSINGCHARACTER,
    WAITINGSTART,
    SETTINGSKULLS,
    SETTINGARENA,
    WAITINGSETUP,
    OTHERTURN,
    YOURTURN,
    DISCARDSPAWN,
    SELECTACTION,
    SELECTBOARDTOSHOW,
    SELECTMOVEMENT,
    SELECTPICKUP,
    SELECTWEAPON,
    SWITCHWEAPON,
    RECHARGEWEAPON,
    PAYMENT,
    RECONNECTING,
    USEPOWERUP,
    SELECTPOWERUPPOSITION,
    SELECTPOWERUPTARGET, USEWEAPON, USEEFFECT;
}
